print("hello\nworld")
print("my name is:\t manha")
print("this is a backslash: \\")
print("he said \'hello\'")
print("12345\rABCDE")
print('this is a valid string')
print("this is a valid string")
print("""this is a valid string""")
print("""Quaid e Azam was a great leader he said "unity, faith and discipline" is very important to us""")
